misc:
  input_list: "examples/example.list"
  output_dir: "examples/output"
  device: "cuda"
audio:
  sr: 16000
vad:
  ref_vad: false
  ref_suffix: ".sad"
  method: "pyannote"
  token: "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"
  onset: 0.5
  offset: 0.5
  min_duration_on: 0.1
  min_duration_off: 0.1
embedding:
  model: "ecapa"
  win_length: 2.0
  hop_length: 0.5
cluster:
  method: "ahc"
  num_cluster: None
  threshold: 0.8
  normalize: true
eval:
  run: true
  p_table: true
  collar: 0.25
  ignore_overlaps: false

