misc:
  input_list: "trials/voxconverse_dev.list"
  output_dir: "trials/voxconverse_dev_result"
  device: "cuda"
audio:
  sr: 16000
vad:
  ref_vad: false
  merge_vad: false
  ref_suffix: ".lab"
  pyannote_token: "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"
  onset: 0.5
  offset: 0.5
  min_duration_on: 0.1
  min_duration_off: 0.1
embedding:
  win_length: 1.5
  hop_length: 0.5
cluster:
  num_cluster: None
  threshold: 0.8
  normalize: true
eval:
  run: true
  p_table: true
  collar: 0.25
  ignore_overlaps: false

