misc:
  input_list: "trials/audio_sample2.list"
  output_dir: "trials/bruno_result_sentence2"
  device: "cuda"
audio:
  sr: 16000
vad:
  ref_vad: true
  merge_vad: true
  ref_suffix: ".lab"
  method: "pyannote"
  token: "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"
  onset: 0.5
  offset: 0.5
  min_duration_on: 0.1
  min_duration_off: 0.1
embedding:
  model: "ecapa"
  win_length: 1.5
  hop_length: 0.5
cluster:
  method: "ahc"
  num_cluster: None
  threshold: 0.91
  normalize: true
eval:
  run: true
  p_table: true
  collar: 0.25
  ignore_overlaps: false

